// Body Studio — the Serenity Hands cast: named adult characters designed in
// Body Studio (full params), used by the game for its people and listed in
// Body Studio's presets. BS.CAST = [{ id, name, identity, pronouns, params, ... }].
//
// Everyone here is an adult (21+), drawn from real human variation: realistic
// heights for their sex, natural figures, ancestry with matching pigmentation.
// Each entry is designed by hand: a face look blended with individual
// features, figure details, hair, eyes, brows, makeup (some bare) and a
// default outfit. `game` is the Serenity Hands identity (IDS key); `identity`
// is Body Studio's (femboys are men in Body Studio's list).
(function () {
  'use strict';
  const BS = (window.BS = window.BS || {});
  const r2 = (v) => Math.round(v * 100) / 100;
  const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
  const BSID = { woman: 'woman', man: 'man', transwoman: 'transwoman', transman: 'transman', nonbinary: 'nonbinary', genderfluid: 'genderfluid', femboy: 'man' };
  const BUILD_LABEL = { petite: 'Petite', slim: 'Slim', athletic: 'Athletic', average: 'Average', curvy: 'Curvy', thick: 'Thick', plus: 'Plus-size', tall: 'Tall', muscular: 'Muscular', stocky: 'Stocky' };

  // c: { id, name, game, pron, age, h (cm), build, anc: [african, asian, caucasian],
  //      look, lk (look amount), face: {tweaks added to the look}, fig: {figure details}, p: {other params}, bio, role }
  function make(c) {
    const p = BS.defaultParams();
    const look = (BS.LOOKS && BS.LOOKS[c.look]) || {}, k = c.lk ?? 0.75, d = {};
    for (const key in look) d[key] = look[key] * k;
    for (const key in c.face || {}) d[key] = (d[key] || 0) + c.face[key];
    Object.assign(d, c.fig || {});
    for (const key in d) d[key] = r2(clamp(d[key], -1, 1));
    const [af, as, ca] = c.anc;
    Object.assign(p, { makeup: 0 }, c.p, {
      name: c.name, identity: BSID[c.game] || 'nonbinary', pronouns: c.pron, age: c.age, heightCm: c.h,
      african: af, asian: as, caucasian: ca, details: d,
    });
    if (p.makeupStyle !== 'none' && !c.p.makeup) p.makeup = 0.6;
    return p;
  }

  const L = [
    // ------------------------------------------------------------ women
    { id: 'sakura', name: 'Sakura', game: 'woman', pron: 'she/her', age: 26, h: 160, build: 'slim', anc: [0, 0.95, 0.05], look: 'pretty', lk: 0.7,
      face: { epicanthus: 0.3, eyefold: -0.25, nosebridge: -0.2, nosewidth: 0.05, 'head-oval': 0.1, cheekvolume: 0.1, mouthwidth: -0.05 },
      fig: { waist: -0.25, hips: 0.1, glutes: 0.2, thighs: 0.05, belly: -0.25, 'shape-neathourglass': 0.35 },
      p: { gender: 0.03, weight: 0.42, muscle: 0.42, proportions: 0.62, skinTone: 0.2, undertone: 0.6, breastSize: 0.5, breastFirmness: 0.6, hairStyle: 'long', hairColor: 'Jet black', hairLength: 0.75, hairVolume: 0.45, curl: 0.05, eyeColor: 'Dark brown', browStyle: 'straight', browThickness: 0.45, lashLength: 0.7, makeupStyle: 'natural', makeup: 0.5, lipColor: 0.45, blush: 0.4, moles: 0.15, outfit: 'dress', outfitColor: '#e8c4cf', outfitColor2: '#3a3340' },
      bio: 'Pastry chef who books a neck massage after every wedding-cake week.' },
    { id: 'amara', name: 'Amara', game: 'woman', pron: 'she/her', age: 29, h: 174, build: 'athletic', anc: [0.92, 0, 0.08], look: 'glam', lk: 0.7,
      face: { nosewidth: 0.35, nostrils: 0.25, upperlip: 0.3, lowerlip: 0.3, cheekbones: 0.1, jawwidth: -0.05, 'head-oval': 0.1 },
      fig: { shoulders: 0.15, waist: -0.35, belly: -0.35, glutes: 0.6, thighs: 0.3, thighmuscle: 0.35, calfmuscle: 0.35, hips: 0.2, upperleglen: 0.2 },
      p: { gender: 0.03, weight: 0.44, muscle: 0.78, proportions: 0.78, skinTone: 0.84, undertone: 0.55, breastSize: 0.48, breastFirmness: 0.62, hairStyle: 'curly', hairColor: 'Soft black', hairLength: 0.55, hairVolume: 0.7, curl: 0.9, eyeColor: 'Dark brown', browStyle: 'arched', browThickness: 0.55, lashLength: 0.8, makeupStyle: 'soft glam', makeup: 0.6, lipColor: 0.55, blush: 0.3, outfit: 'sport', outfitColor: '#1f2a44', outfitColor2: '#2b2d33' },
      bio: 'Physiotherapy student and weekend sprinter — she knows exactly which hamstring hurts.' },
    { id: 'camila', name: 'Camila', game: 'woman', pron: 'she/her', age: 27, h: 163, build: 'curvy', anc: [0.15, 0.3, 0.55], look: 'glam', lk: 0.75,
      face: { upperlip: 0.15, lowerlip: 0.2, nosewidth: 0.05, cheekvolume: 0.1, dimples: 0.25 },
      fig: { 'shape-hourglass': 0.65, waist: -0.4, hips: 0.45, glutes: 0.65, thighs: 0.35, belly: -0.15, breastpos: -0.05 },
      p: { gender: 0.02, weight: 0.6, muscle: 0.45, proportions: 0.62, skinTone: 0.38, undertone: 0.62, breastSize: 0.66, breastFirmness: 0.56, hairStyle: 'wavy', hairColor: 'Dark brown', hairLength: 0.8, hairVolume: 0.65, curl: 0.35, eyeColor: 'Brown', browStyle: 'arched', browThickness: 0.6, lashLength: 0.9, makeupStyle: 'bold lip', makeup: 0.75, lipstick: '#9e1c2e', lipColor: 0.6, blush: 0.35, moles: 0.35, outfit: 'dress', outfitColor: '#7a1f2b', outfitColor2: '#1e1e22' },
      bio: 'Salsa teacher with a laugh you can hear from the lobby.' },
    { id: 'ingrid', name: 'Ingrid', game: 'woman', pron: 'she/her', age: 31, h: 177, build: 'tall', anc: [0, 0, 1], look: 'model', lk: 0.6,
      face: { nosebridge: 0.1, noselength: 0.1, eyespacing: 0.05, mouthwidth: 0.05, 'head-rectangular': 0.15, chinheight: 0.1 },
      fig: { waist: -0.2, belly: -0.25, shoulders: 0.1, hips: 0.05, glutes: 0.25, upperleglen: 0.25, lowerleglen: 0.15, 'shape-rectangle': 0.3 },
      p: { gender: 0.04, weight: 0.45, muscle: 0.58, proportions: 0.8, skinTone: 0.05, undertone: 0.42, breastSize: 0.45, breastFirmness: 0.55, freckles: 0.2, hairStyle: 'braid', hairColor: 'Golden blonde', hairLength: 0.8, hairVolume: 0.5, curl: 0.1, eyeColor: 'Light blue', browStyle: 'natural', browThickness: 0.4, lashLength: 0.6, makeupStyle: 'natural', makeup: 0.4, lipColor: 0.38, blush: 0.35, outfit: 'casual', outfitColor: '#d9c6a5', outfitColor2: '#3b5c8a' },
      bio: 'Architect from Bergen who sketches the spa\'s ceiling beams while she waits.' },
    { id: 'priya', name: 'Priya', game: 'woman', pron: 'she/her', age: 28, h: 158, build: 'curvy', anc: [0.1, 0.55, 0.35], look: 'exotic', lk: 0.65,
      face: { epicanthus: -0.15, eyesize: 0.08, nosewidth: 0.1, nosebridge: 0.1, upperlip: 0.1, lowerlip: 0.15, 'head-oval': 0.25, browheight: -0.05 },
      fig: { 'shape-pear': 0.4, waist: -0.3, hips: 0.4, glutes: 0.45, thighs: 0.35, belly: -0.1 },
      p: { gender: 0.02, weight: 0.55, muscle: 0.4, proportions: 0.6, skinTone: 0.46, undertone: 0.66, breastSize: 0.6, breastFirmness: 0.58, hairStyle: 'braid', hairColor: 'Jet black', hairLength: 0.9, hairVolume: 0.6, curl: 0.2, eyeColor: 'Dark brown', browStyle: 'thick', browThickness: 0.65, lashLength: 0.85, makeupStyle: 'smoky eye', makeup: 0.65, lipColor: 0.5, blush: 0.25, moles: 0.2, outfit: 'dress', outfitColor: '#2f5a4a', outfitColor2: '#c9a465' },
      bio: 'Software engineer by day, Bharatanatyam dancer by night.' },
    { id: 'mei', name: 'Mei', game: 'woman', pron: 'she/her', age: 24, h: 165, build: 'slim', anc: [0, 0.97, 0.03], look: 'pretty', lk: 0.6,
      face: { epicanthus: 0.4, eyefold: -0.35, nosebridge: -0.3, nosewidth: 0.05, cheekbones: 0.15, 'head-diamond': 0.2, jawwidth: -0.05 },
      fig: { waist: -0.2, belly: -0.3, hips: -0.05, glutes: 0.1, thighs: -0.05, 'shape-column': 0.3 },
      p: { gender: 0.04, weight: 0.36, muscle: 0.4, proportions: 0.65, skinTone: 0.18, undertone: 0.55, breastSize: 0.42, breastFirmness: 0.62, hairStyle: 'bob', hairColor: 'Jet black', hairLength: 0.45, hairVolume: 0.45, curl: 0, eyeColor: 'Dark brown', browStyle: 'straight', browThickness: 0.5, lashLength: 0.65, makeupStyle: 'everyday', makeup: 0.5, lipColor: 0.45, blush: 0.35, outfit: 'casual', outfitColor: '#f2efe9', outfitColor2: '#46546b' },
      bio: 'Marine-biology grad student who spends too long hunched over a microscope.' },
    { id: 'aaliyah', name: 'Aaliyah', game: 'woman', pron: 'she/her', age: 33, h: 168, build: 'thick', anc: [0.85, 0, 0.15], look: 'soft', lk: 0.6,
      face: { nosewidth: 0.3, upperlip: 0.35, lowerlip: 0.35, cheekbones: 0.25, cheekvolume: 0.1, 'head-round': 0.1 },
      fig: { 'shape-hourglass': 0.7, waist: -0.15, hips: 0.55, glutes: 0.75, thighs: 0.5, thighfat: 0.2, belly: 0.05, armfat: 0.15, breastpos: -0.1 },
      p: { gender: 0.02, weight: 0.74, muscle: 0.42, proportions: 0.58, skinTone: 0.72, undertone: 0.6, breastSize: 0.7, breastFirmness: 0.48, hairStyle: 'braid', hairColor: 'Soft black', hairLength: 0.85, hairVolume: 0.65, curl: 0.6, eyeColor: 'Dark brown', browStyle: 'arched', browThickness: 0.55, lashLength: 0.9, makeupStyle: 'glam', makeup: 0.7, lipColor: 0.55, blush: 0.25, outfit: 'dress', outfitColor: '#c9a465', outfitColor2: '#1e1e22' },
      bio: 'Owns the bakery across town and swears by the hot-stone treatment.' },
    { id: 'nora', name: 'Nora', game: 'woman', pron: 'she/her', age: 38, h: 164, build: 'average', anc: [0, 0, 1], look: 'girlnextdoor', lk: 0.65,
      face: { headage: 0.15, nosetip: 0.05, upperlip: -0.05, laughlines: 0.25, cheekbones: 0.15, 'head-oval': 0.1 },
      fig: { waist: -0.05, belly: 0.05, hips: 0.2, glutes: 0.25, thighs: 0.15, breastpos: -0.15 },
      p: { gender: 0.03, weight: 0.55, muscle: 0.45, proportions: 0.55, skinTone: 0.02, undertone: 0.45, breastSize: 0.6, breastFirmness: 0.42, freckles: 0.55, moles: 0.3, hairStyle: 'wavy', hairColor: 'Copper red', hairLength: 0.65, hairVolume: 0.6, curl: 0.4, eyeColor: 'Green', browStyle: 'natural', browThickness: 0.4, lashLength: 0.6, makeupStyle: 'natural', makeup: 0.35, lipColor: 0.4, blush: 0.4, outfit: 'casual', outfitColor: '#2f5a4a', outfitColor2: '#22252c' },
      bio: 'Veterinary surgeon: long shifts, steady hands, very sore shoulders.' },
    { id: 'leila', name: 'Leila', game: 'woman', pron: 'she/her', age: 30, h: 167, build: 'slim', anc: [0.1, 0.12, 0.78], look: 'glam', lk: 0.7,
      face: { nosebridge: 0.15, nosehump: 0.15, noselength: 0.1, eyesize: 0.06, upperlip: 0.1, lowerlip: 0.1, browheight: -0.05, 'head-oval': 0.15 },
      fig: { 'shape-neathourglass': 0.5, waist: -0.35, belly: -0.25, hips: 0.2, glutes: 0.35, thighs: 0.1 },
      p: { gender: 0.02, weight: 0.45, muscle: 0.42, proportions: 0.7, skinTone: 0.3, undertone: 0.58, breastSize: 0.58, breastFirmness: 0.56, hairStyle: 'wavy', hairColor: 'Dark brown', hairLength: 0.85, hairVolume: 0.6, curl: 0.3, eyeColor: 'Hazel', browStyle: 'arched', browThickness: 0.75, lashLength: 0.9, makeupStyle: 'soft glam', makeup: 0.6, lipColor: 0.5, blush: 0.3, moles: 0.35, outfit: 'formal', outfitColor: '#e8e2d6', outfitColor2: '#1e1e22' },
      bio: 'Human-rights lawyer who reads poetry on the train home.' },
    { id: 'zoe', name: 'Zoe', game: 'woman', pron: 'she/her', age: 25, h: 161, build: 'athletic', anc: [0, 0.05, 0.95], look: 'girlnextdoor', lk: 0.55,
      face: { cheekbones: 0.25, jawline: 0.15, nosetip: 0.05, mouthwidth: 0.05, chinprominent: 0.1, 'head-oval': 0.1 },
      fig: { shoulders: 0.15, waist: -0.3, belly: -0.35, glutes: 0.45, thighs: 0.25, thighmuscle: 0.4, armmuscle: 0.3, forearm: 0.3, calfmuscle: 0.3 },
      p: { gender: 0.04, weight: 0.4, muscle: 0.8, proportions: 0.6, skinTone: 0.12, undertone: 0.5, breastSize: 0.42, breastFirmness: 0.62, freckles: 0.25, hairStyle: 'ponytail', hairColor: 'Light brown', hairLength: 0.6, hairVolume: 0.5, curl: 0.15, eyeColor: 'Blue', browStyle: 'natural', browThickness: 0.45, lashLength: 0.6, makeupStyle: 'none', lipColor: 0.38, blush: 0.35, outfit: 'sport', outfitColor: '#2d7a52', outfitColor2: '#22252c' },
      bio: 'Climbing-gym instructor with permanently chalky hands.' },
    { id: 'valentina', name: 'Valentina', game: 'woman', pron: 'she/her', age: 35, h: 170, build: 'curvy', anc: [0, 0, 1], look: 'glam', lk: 0.8,
      face: { nosebridge: 0.1, noselength: 0.08, nosehump: 0.1, upperlip: 0.15, lowerlip: 0.15, headage: 0.05, 'head-oval': 0.2 },
      fig: { 'shape-hourglass': 0.6, waist: -0.3, hips: 0.4, glutes: 0.5, thighs: 0.25, belly: -0.05, breastpos: -0.1 },
      p: { gender: 0.01, weight: 0.57, muscle: 0.45, proportions: 0.7, skinTone: 0.24, undertone: 0.62, breastSize: 0.64, breastFirmness: 0.48, hairStyle: 'long', hairColor: 'Chestnut', hairLength: 0.85, hairVolume: 0.65, curl: 0.25, eyeColor: 'Brown', browStyle: 'arched', browThickness: 0.55, lashLength: 0.9, makeupStyle: 'glam', makeup: 0.75, lipColor: 0.6, blush: 0.3, moles: 0.4, outfit: 'dress', outfitColor: '#1e1e22', outfitColor2: '#7a1f2b' },
      bio: 'Opera mezzo-soprano between seasons: the posture of a queen, the knots of a mortal.' },
    { id: 'hana', name: 'Hana', game: 'woman', pron: 'she/her', age: 29, h: 169, build: 'slim', anc: [0, 0.96, 0.04], look: 'model', lk: 0.7,
      face: { epicanthus: 0.35, eyefold: -0.3, nosebridge: -0.15, cheekbones: 0.1, jawwidth: -0.1, 'head-invertedtriangular': 0.2 },
      fig: { waist: -0.3, belly: -0.35, hips: 0, glutes: 0.2, upperleglen: 0.2, 'shape-column': 0.35 },
      p: { gender: 0.03, weight: 0.35, muscle: 0.42, proportions: 0.85, skinTone: 0.16, undertone: 0.52, breastSize: 0.42, breastFirmness: 0.6, hairStyle: 'long', hairColor: 'Soft black', hairLength: 0.85, hairVolume: 0.4, curl: 0, eyeColor: 'Dark brown', browStyle: 'straight', browThickness: 0.5, lashLength: 0.75, makeupStyle: 'editorial', makeup: 0.65, lipColor: 0.55, blush: 0.4, outfit: 'formal', outfitColor: '#e8e2d6', outfitColor2: '#2d3646' },
      bio: 'Fashion buyer who flies between Seoul and Milan every month.' },
    { id: 'fatima', name: 'Fatima', game: 'woman', pron: 'she/her', age: 27, h: 162, build: 'average', anc: [0.28, 0.07, 0.65], look: 'pretty', lk: 0.65,
      face: { eyesize: 0.06, nosebridge: 0.1, noselength: 0.05, upperlip: 0.15, lowerlip: 0.15, cheekbones: 0.15, 'head-oval': 0.15 },
      fig: { waist: -0.2, belly: -0.1, hips: 0.25, glutes: 0.35, thighs: 0.2, 'shape-pear': 0.25 },
      p: { gender: 0.03, weight: 0.5, muscle: 0.48, proportions: 0.6, skinTone: 0.42, undertone: 0.62, breastSize: 0.55, breastFirmness: 0.58, hairStyle: 'curly', hairColor: 'Dark brown', hairLength: 0.6, hairVolume: 0.6, curl: 0.65, eyeColor: 'Amber', browStyle: 'thick', browThickness: 0.7, lashLength: 0.85, makeupStyle: 'everyday', makeup: 0.5, lipColor: 0.5, blush: 0.25, outfit: 'casual', outfitColor: '#6b2d3a', outfitColor2: '#22252c' },
      bio: 'Paramedic who runs on mint tea and twelve-hour shifts.' },
    { id: 'grace', name: 'Grace', game: 'woman', pron: 'she/her', age: 45, h: 170, build: 'plus', anc: [0.9, 0, 0.1], look: 'soft', lk: 0.6,
      face: { nosewidth: 0.3, upperlip: 0.25, lowerlip: 0.3, headage: 0.2, laughlines: 0.35, cheekbones: 0.2, 'head-round': 0.15 },
      fig: { 'shape-apple': 0.35, waist: 0.25, belly: 0.35, hips: 0.5, glutes: 0.55, thighs: 0.5, armfat: 0.35, doublechin: 0.15, breastpos: -0.25 },
      p: { gender: 0.03, weight: 0.92, muscle: 0.38, proportions: 0.5, skinTone: 0.8, undertone: 0.55, breastSize: 0.76, breastFirmness: 0.36, moles: 0.2, hairStyle: 'afro', hairColor: 'Soft black', hairLength: 0.35, hairVolume: 0.6, curl: 1, eyeColor: 'Dark brown', browStyle: 'natural', browThickness: 0.45, lashLength: 0.7, makeupStyle: 'bold lip', makeup: 0.6, lipstick: '#8a2c4a', lipColor: 0.55, blush: 0.2, outfit: 'dress', outfitColor: '#2d3646', outfitColor2: '#c9a465' },
      bio: 'Head teacher and gospel-choir alto who comes here to finally sit still.' },
    { id: 'rin', name: 'Rin', game: 'woman', pron: 'she/her', age: 27, h: 156, build: 'petite', anc: [0, 0.95, 0.05], look: 'pretty', lk: 0.6,
      face: { epicanthus: 0.3, eyefold: -0.25, nosebridge: -0.2, cheekbones: 0.2, jawline: 0.1, chinheight: 0.05, 'head-oval': 0.15 },
      fig: { waist: -0.2, belly: -0.2, hips: 0.1, glutes: 0.2, thighs: 0.05, 'shape-neathourglass': 0.3 },
      p: { gender: 0.03, weight: 0.4, muscle: 0.4, proportions: 0.62, skinTone: 0.22, undertone: 0.6, breastSize: 0.46, breastFirmness: 0.6, hairStyle: 'bun', hairColor: 'Soft black', hairLength: 0.7, hairVolume: 0.5, curl: 0.05, eyeColor: 'Brown', browStyle: 'natural', browThickness: 0.5, lashLength: 0.7, makeupStyle: 'everyday', makeup: 0.5, lipColor: 0.5, blush: 0.4, moles: 0.15, nailColor: '#c94f6a', outfit: 'casual', outfitColor: '#e7a5b8', outfitColor2: '#2d3646' },
      bio: 'Comic artist who draws all day — ask her about her right shoulder.' },
    { id: 'elena', name: 'Elena', game: 'woman', pron: 'she/her', age: 52, h: 165, build: 'average', anc: [0.03, 0.02, 0.95], look: 'model', lk: 0.5,
      face: { headage: 0.35, laughlines: 0.3, eyebags: 0.2, nosebridge: 0.1, nosehump: 0.1, cheekbones: 0.2, upperlip: -0.1 },
      fig: { waist: 0, belly: 0.1, hips: 0.2, glutes: 0.15, thighs: 0.1, necklen: 0.2, breastpos: -0.25, 'shape-rectangle': 0.25 },
      p: { gender: 0.03, weight: 0.5, muscle: 0.5, proportions: 0.72, skinTone: 0.2, undertone: 0.55, breastSize: 0.55, breastFirmness: 0.3, moles: 0.4, hairStyle: 'bun', hairColor: 'Grey', hairLength: 0.6, hairVolume: 0.45, curl: 0.15, eyeColor: 'Hazel', browStyle: 'thin', browThickness: 0.4, lashLength: 0.6, makeupStyle: 'natural', makeup: 0.45, lipColor: 0.45, blush: 0.3, outfit: 'formal', outfitColor: '#6d5a6e', outfitColor2: '#1e1e22' },
      bio: 'Retired ballet mistress who still corrects everyone\'s posture, gently.' },
    { id: 'leilani', name: 'Leilani', game: 'woman', pron: 'she/her', age: 28, h: 171, build: 'athletic', anc: [0.2, 0.6, 0.2], look: 'exotic', lk: 0.6,
      face: { nosewidth: 0.2, upperlip: 0.2, lowerlip: 0.2, epicanthus: -0.05, cheekbones: 0.2, jawwidth: 0.05, 'head-oval': 0.1 },
      fig: { shoulders: 0.25, lats: 0.2, waist: -0.2, belly: -0.25, hips: 0.3, glutes: 0.5, thighs: 0.35, thighmuscle: 0.3, armmuscle: 0.25 },
      p: { gender: 0.04, weight: 0.55, muscle: 0.72, proportions: 0.65, skinTone: 0.5, undertone: 0.66, breastSize: 0.58, breastFirmness: 0.58, hairStyle: 'wavy', hairColor: 'Dark brown', hairLength: 0.95, hairVolume: 0.7, curl: 0.45, eyeColor: 'Brown', browStyle: 'natural', browThickness: 0.55, lashLength: 0.75, makeupStyle: 'natural', makeup: 0.35, lipColor: 0.48, blush: 0.25, outfit: 'sport', outfitColor: '#2b4f9c', outfitColor2: '#f2efe9' },
      bio: 'Outrigger paddler and surf instructor; her shoulders do all the work.' },
    // ------------------------------------------------------------ femboys
    { id: 'felix', name: 'Felix', game: 'femboy', pron: 'he/him', age: 23, h: 173, build: 'slim', anc: [0, 0, 1], look: 'prettyboy', lk: 0.85,
      face: { eyesize: 0.04, lowerlip: 0.05, nosewidth: -0.1, jawwidth: -0.15, cheekbones: 0.1, 'head-oval': 0.1 },
      fig: { shoulders: -0.15, waist: -0.3, belly: -0.35, hips: 0.1, glutes: 0.2, thighs: 0.05, neckthick: -0.2 },
      p: { gender: 0.64, weight: 0.36, muscle: 0.45, proportions: 0.65, skinTone: 0.08, undertone: 0.5, breastSize: 0.5, breastFirmness: 0.5, hairStyle: 'medium', hairColor: 'Golden blonde', hairLength: 0.6, hairVolume: 0.55, curl: 0.2, eyeColor: 'Blue', browStyle: 'natural', browThickness: 0.4, lashLength: 0.7, makeupStyle: 'natural', makeup: 0.35, lipColor: 0.45, blush: 0.35, bodyHair: 0.03, nailColor: '#b79be6', outfit: 'casual', outfitColor: '#e3a3b5', outfitColor2: '#2d3646' },
      bio: 'Barista and synth-pop producer with lilac nails and opinions about oat milk.' },
    { id: 'ren', name: 'Ren', game: 'femboy', pron: 'he/they', age: 25, h: 168, build: 'slim', anc: [0, 0.95, 0.05], look: 'prettyboy', lk: 0.8,
      face: { epicanthus: 0.35, eyefold: -0.3, nosebridge: -0.25, jawwidth: -0.15, upperlip: 0.05, cheekbones: 0.1, 'head-oval': 0.15 },
      fig: { shoulders: -0.2, waist: -0.3, belly: -0.3, hips: 0.1, glutes: 0.15, neckthick: -0.2 },
      p: { gender: 0.62, weight: 0.35, muscle: 0.42, proportions: 0.62, skinTone: 0.2, undertone: 0.55, breastSize: 0.5, breastFirmness: 0.5, hairStyle: 'bob', hairColor: 'Soft black', hairLength: 0.5, hairVolume: 0.5, curl: 0, eyeColor: 'Dark brown', browStyle: 'straight', browThickness: 0.45, lashLength: 0.7, makeupStyle: 'everyday', makeup: 0.45, lipColor: 0.48, blush: 0.4, bodyHair: 0.02, outfit: 'casual', outfitColor: '#1e1e22', outfitColor2: '#7a6a9a' },
      bio: 'Cosplay tailor whose seams are better than most shops\'.' },
    { id: 'kai', name: 'Kai', game: 'femboy', pron: 'he/him', age: 26, h: 170, build: 'athletic', anc: [0.05, 0.75, 0.2], look: 'prettyboy', lk: 0.75,
      face: { epicanthus: 0.15, nosewidth: 0.1, upperlip: 0.1, lowerlip: 0.1, cheekbones: 0.2, 'head-oval': 0.1 },
      fig: { shoulders: -0.05, waist: -0.3, belly: -0.35, hips: 0.15, glutes: 0.4, thighs: 0.2, thighmuscle: 0.3, calfmuscle: 0.25 },
      p: { gender: 0.66, weight: 0.4, muscle: 0.68, proportions: 0.65, skinTone: 0.4, undertone: 0.65, breastSize: 0.5, breastFirmness: 0.5, hairStyle: 'medium', hairColor: 'Dark brown', hairLength: 0.45, hairVolume: 0.55, curl: 0.25, eyeColor: 'Brown', browStyle: 'natural', browThickness: 0.5, lashLength: 0.6, makeupStyle: 'none', lipColor: 0.42, blush: 0.25, bodyHair: 0.05, outfit: 'sport', outfitColor: '#22252c', outfitColor2: '#a33b2a' },
      bio: 'Dance-crew captain; it is leg day every day.' },
    { id: 'theo', name: 'Theo', game: 'femboy', pron: 'he/him', age: 28, h: 179, build: 'tall', anc: [0, 0, 1], look: 'prettyboy', lk: 0.7,
      face: { noselength: 0.1, nosebridge: 0.05, jawline: 0.1, cheekbones: 0.2, cheekinner: -0.15, 'head-rectangular': 0.15 },
      fig: { shoulders: -0.05, waist: -0.25, belly: -0.35, hips: 0.05, glutes: 0.15, upperleglen: 0.2, neckthick: -0.15 },
      p: { gender: 0.7, weight: 0.36, muscle: 0.48, proportions: 0.75, skinTone: 0.06, undertone: 0.45, breastSize: 0.5, breastFirmness: 0.5, hairStyle: 'long', hairColor: 'Light brown', hairLength: 0.55, hairVolume: 0.5, curl: 0.15, eyeColor: 'Grey-green', browStyle: 'natural', browThickness: 0.5, lashLength: 0.6, makeupStyle: 'graphic liner', makeup: 0.55, lipColor: 0.4, blush: 0.25, bodyHair: 0.06, nailColor: '#1e1e22', outfit: 'casual', outfitColor: '#1e1e22', outfitColor2: '#46546b' },
      bio: 'Indie-band bassist; his eyeliner is sharper than his basslines.' },
    { id: 'asher', name: 'Asher', game: 'femboy', pron: 'he/him', age: 24, h: 175, build: 'slim', anc: [0.5, 0, 0.5], look: 'prettyboy', lk: 0.75,
      face: { nosewidth: 0.15, upperlip: 0.2, lowerlip: 0.2, cheekbones: 0.15, jawwidth: -0.1, 'head-oval': 0.1 },
      fig: { shoulders: -0.1, waist: -0.3, belly: -0.35, hips: 0.1, glutes: 0.3, thighs: 0.1, neckthick: -0.1 },
      p: { gender: 0.66, weight: 0.38, muscle: 0.55, proportions: 0.7, skinTone: 0.48, undertone: 0.58, breastSize: 0.5, breastFirmness: 0.5, hairStyle: 'curly', hairColor: 'Dark brown', hairLength: 0.5, hairVolume: 0.65, curl: 0.85, eyeColor: 'Hazel', browStyle: 'natural', browThickness: 0.55, lashLength: 0.7, makeupStyle: 'natural', makeup: 0.3, lipColor: 0.45, blush: 0.2, freckles: 0.15, bodyHair: 0.04, outfit: 'casual', outfitColor: '#c9b79c', outfitColor2: '#22252c' },
      bio: 'Yoga instructor who still can\'t touch his toes after a long weekend.' },
    { id: 'yuki', name: 'Yuki', game: 'femboy', pron: 'he/they', age: 29, h: 166, build: 'slim', anc: [0, 0.95, 0.05], look: 'prettyboy', lk: 0.8,
      face: { epicanthus: 0.3, eyefold: -0.3, nosebridge: -0.2, jawwidth: -0.2, cheekbones: 0.15, mouthwidth: -0.05, 'head-oval': 0.15 },
      fig: { shoulders: -0.2, waist: -0.35, belly: -0.3, hips: 0.15, glutes: 0.25, neckthick: -0.2 },
      p: { gender: 0.61, weight: 0.36, muscle: 0.4, proportions: 0.62, skinTone: 0.17, undertone: 0.5, breastSize: 0.5, breastFirmness: 0.5, hairStyle: 'ponytail', hairColor: 'Pastel pink', hairLength: 0.65, hairVolume: 0.5, curl: 0.05, eyeColor: 'Dark brown', browStyle: 'thin', browThickness: 0.4, lashLength: 0.75, makeupStyle: 'everyday', makeup: 0.5, lipColor: 0.5, blush: 0.45, bodyHair: 0.02, nailColor: '#f3a3c4', outfit: 'casual', outfitColor: '#f2d0d8', outfitColor2: '#46546b' },
      bio: 'Pastry-school graduate who makes the café\'s best matcha rolls.' },
    { id: 'milo', name: 'Milo', game: 'femboy', pron: 'he/him', age: 22, h: 174, build: 'slim', anc: [0.05, 0, 0.95], look: 'prettyboy', lk: 0.7,
      face: { nosebridge: 0.1, nosehump: 0.1, cheekbones: 0.2, jawline: 0.1, chinprominent: 0.1, 'head-oval': 0.15 },
      fig: { shoulders: -0.1, waist: -0.25, belly: -0.3, hips: 0.05, glutes: 0.15, neckthick: -0.15 },
      p: { gender: 0.68, weight: 0.36, muscle: 0.45, proportions: 0.68, skinTone: 0.15, undertone: 0.55, breastSize: 0.5, breastFirmness: 0.5, hairStyle: 'bob', hairColor: 'Chestnut', hairLength: 0.5, hairVolume: 0.55, curl: 0.3, eyeColor: 'Hazel', browStyle: 'natural', browThickness: 0.5, lashLength: 0.65, makeupStyle: 'none', lipColor: 0.42, blush: 0.3, moles: 0.3, bodyHair: 0.05, outfit: 'formal', outfitColor: '#f2efe9', outfitColor2: '#6a4b35' },
      bio: 'Literature student who works weekends at the flower market.' },
    // ------------------------------------------------------------ trans women
    { id: 'luna', name: 'Luna', game: 'transwoman', pron: 'she/her', age: 27, h: 174, build: 'curvy', anc: [0.35, 0.1, 0.55], look: 'glam', lk: 0.75,
      face: { upperlip: 0.15, lowerlip: 0.2, nosewidth: 0.05, jawwidth: -0.1, cheekbones: 0.15, 'head-oval': 0.15 },
      fig: { 'shape-hourglass': 0.45, waist: -0.35, hips: 0.35, glutes: 0.5, thighs: 0.25, belly: -0.2 },
      p: { gender: 0.16, weight: 0.52, muscle: 0.5, proportions: 0.7, skinTone: 0.46, undertone: 0.62, breastSize: 0.6, breastFirmness: 0.6, hairStyle: 'wavy', hairColor: 'Dark brown', hairLength: 0.9, hairVolume: 0.7, curl: 0.4, eyeColor: 'Brown', browStyle: 'arched', browThickness: 0.5, lashLength: 0.9, makeupStyle: 'soft glam', makeup: 0.65, lipColor: 0.55, blush: 0.35, bodyHair: 0.02, outfit: 'dress', outfitColor: '#a33b2a', outfitColor2: '#1e1e22' },
      bio: 'Wedding photographer from Recife; her camera bag weighs a ton.' },
    { id: 'aria', name: 'Aria', game: 'transwoman', pron: 'she/her', age: 24, h: 170, build: 'slim', anc: [0, 0.9, 0.1], look: 'pretty', lk: 0.7,
      face: { epicanthus: 0.3, eyefold: -0.25, nosebridge: -0.15, jawwidth: -0.1, cheekbones: 0.15, 'head-oval': 0.15 },
      fig: { waist: -0.3, belly: -0.3, hips: 0.2, glutes: 0.25, thighs: 0.1, 'shape-neathourglass': 0.3 },
      p: { gender: 0.18, weight: 0.4, muscle: 0.42, proportions: 0.65, skinTone: 0.18, undertone: 0.55, breastSize: 0.48, breastFirmness: 0.62, hairStyle: 'long', hairColor: 'Violet', hairLength: 0.8, hairVolume: 0.5, curl: 0.05, eyeColor: 'Dark brown', browStyle: 'straight', browThickness: 0.45, lashLength: 0.8, makeupStyle: 'everyday', makeup: 0.55, lipColor: 0.5, blush: 0.4, bodyHair: 0.02, outfit: 'casual', outfitColor: '#7a6a9a', outfitColor2: '#1e1e22' },
      bio: 'Esports caster who talks faster than anyone you have ever met.' },
    { id: 'jade', name: 'Jade', game: 'transwoman', pron: 'she/her', age: 31, h: 179, build: 'athletic', anc: [0, 0, 1], look: 'model', lk: 0.6,
      face: { nosebridge: 0.05, cheekbones: 0.15, jawwidth: -0.05, browridge: -0.15, upperlip: 0.05, 'head-oval': 0.15 },
      fig: { shoulders: 0.1, waist: -0.2, belly: -0.3, hips: 0.2, glutes: 0.35, thighs: 0.15, armmuscle: 0.2, upperleglen: 0.15 },
      p: { gender: 0.22, weight: 0.44, muscle: 0.7, proportions: 0.75, skinTone: 0.1, undertone: 0.5, breastSize: 0.48, breastFirmness: 0.6, freckles: 0.1, hairStyle: 'ponytail', hairColor: 'Dark blonde', hairLength: 0.7, hairVolume: 0.5, curl: 0.2, eyeColor: 'Green', browStyle: 'natural', browThickness: 0.45, lashLength: 0.7, makeupStyle: 'natural', makeup: 0.4, lipColor: 0.42, blush: 0.3, bodyHair: 0.03, outfit: 'sport', outfitColor: '#3b5c8a', outfitColor2: '#22252c' },
      bio: 'Marine engineer and open-water swimmer from Perth.' },
    { id: 'vivian', name: 'Vivian', game: 'transwoman', pron: 'she/her', age: 36, h: 176, build: 'slim', anc: [0.88, 0, 0.12], look: 'model', lk: 0.75,
      face: { nosewidth: 0.2, upperlip: 0.25, lowerlip: 0.25, cheekbones: 0.15, jawwidth: -0.1, 'head-diamond': 0.15 },
      fig: { waist: -0.3, belly: -0.3, hips: 0.2, glutes: 0.35, thighs: 0.15, necklen: 0.15, 'shape-neathourglass': 0.35 },
      p: { gender: 0.15, weight: 0.42, muscle: 0.48, proportions: 0.85, skinTone: 0.82, undertone: 0.5, breastSize: 0.55, breastFirmness: 0.55, hairStyle: 'bob', hairColor: 'Jet black', hairLength: 0.45, hairVolume: 0.45, curl: 0.1, eyeColor: 'Dark brown', browStyle: 'arched', browThickness: 0.45, lashLength: 0.9, makeupStyle: 'glam', makeup: 0.75, lipColor: 0.55, blush: 0.25, bodyHair: 0.02, outfit: 'formal', outfitColor: '#c9a465', outfitColor2: '#1e1e22' },
      bio: 'Runs a boutique PR agency and never misses her Friday appointment.' },
    { id: 'natsuki', name: 'Natsuki', game: 'transwoman', pron: 'she/her', age: 26, h: 168, build: 'average', anc: [0, 0.95, 0.05], look: 'girlnextdoor', lk: 0.7,
      face: { epicanthus: 0.3, eyefold: -0.2, nosebridge: -0.2, cheekvolume: 0.1, jawwidth: -0.1, 'head-round': 0.1 },
      fig: { waist: -0.15, belly: -0.15, hips: 0.25, glutes: 0.3, thighs: 0.2, 'shape-pear': 0.25 },
      p: { gender: 0.2, weight: 0.5, muscle: 0.42, proportions: 0.6, skinTone: 0.22, undertone: 0.58, breastSize: 0.52, breastFirmness: 0.6, hairStyle: 'long', hairColor: 'Dark brown', hairLength: 0.7, hairVolume: 0.5, curl: 0.1, eyeColor: 'Brown', browStyle: 'natural', browThickness: 0.5, lashLength: 0.75, makeupStyle: 'everyday', makeup: 0.5, lipColor: 0.48, blush: 0.45, bodyHair: 0.02, outfit: 'casual', outfitColor: '#d9d4cc', outfitColor2: '#3b5c8a' },
      bio: 'Video-game composer who hums her own soundtracks under her breath.' },
    { id: 'seraphina', name: 'Seraphina', game: 'transwoman', pron: 'she/her', age: 42, h: 172, build: 'curvy', anc: [0, 0, 1], look: 'glam', lk: 0.7,
      face: { headage: 0.2, laughlines: 0.25, nosebridge: 0.1, nosehump: 0.1, upperlip: 0.1, lowerlip: 0.15, 'head-oval': 0.15 },
      fig: { 'shape-hourglass': 0.4, waist: -0.15, belly: 0.05, hips: 0.35, glutes: 0.4, thighs: 0.3, breastpos: -0.1 },
      p: { gender: 0.2, weight: 0.6, muscle: 0.45, proportions: 0.62, skinTone: 0.26, undertone: 0.6, breastSize: 0.6, breastFirmness: 0.48, moles: 0.3, hairStyle: 'wavy', hairColor: 'Auburn', hairLength: 0.75, hairVolume: 0.65, curl: 0.35, eyeColor: 'Hazel', browStyle: 'arched', browThickness: 0.5, lashLength: 0.8, makeupStyle: 'bold lip', makeup: 0.7, lipstick: '#a3282f', lipColor: 0.55, blush: 0.3, bodyHair: 0.03, outfit: 'dress', outfitColor: '#2f5a4a', outfitColor2: '#c9a465' },
      bio: 'Chef-owner of a little trattoria: kitchen burns on her forearms and stories for days.' },
    // ------------------------------------------------------------ men
    { id: 'marcus', name: 'Marcus', game: 'man', pron: 'he/him', age: 33, h: 187, build: 'muscular', role: 'guard', anc: [0.9, 0, 0.1], look: 'rugged', lk: 0.75,
      face: { nosewidth: 0.3, upperlip: 0.25, lowerlip: 0.25, cheekbones: 0.1, 'head-square': 0.1 },
      fig: { shoulders: 0.45, vshape: 0.5, pecs: 0.45, lats: 0.4, armmuscle: 0.45, biceps: 0.3, forearm: 0.35, glutes: 0.3, thighmuscle: 0.35, neckthick: 0.3, belly: -0.3 },
      p: { gender: 1, weight: 0.6, muscle: 0.92, proportions: 0.72, skinTone: 0.8, undertone: 0.5, breastSize: 0.5, breastFirmness: 0.5, hairStyle: 'buzz', hairColor: 'Soft black', hairLength: 0.2, hairVolume: 0.5, curl: 0.9, eyeColor: 'Dark brown', browStyle: 'thick', browThickness: 0.65, lashLength: 0.45, makeupStyle: 'none', lipColor: 0.38, blush: 0.12, bodyHair: 0.35, beard: 'short', outfit: 'casual', outfitColor: '#2d3646', outfitColor2: '#22252c' },
      bio: 'Firefighter and amateur boxer who finally admits he needs this.' },
    { id: 'diego', name: 'Diego', game: 'man', pron: 'he/him', age: 29, h: 176, build: 'athletic', anc: [0.1, 0.35, 0.55], look: 'rugged', lk: 0.55,
      face: { nosebridge: 0.1, upperlip: 0.1, lowerlip: 0.1, cheekbones: 0.2, dimples: 0.2, 'head-oval': 0.15 },
      fig: { shoulders: 0.25, vshape: 0.35, pecs: 0.3, armmuscle: 0.25, belly: -0.25, glutes: 0.2, calfmuscle: 0.2 },
      p: { gender: 0.97, weight: 0.5, muscle: 0.75, proportions: 0.65, skinTone: 0.4, undertone: 0.62, breastSize: 0.5, breastFirmness: 0.5, hairStyle: 'short', hairColor: 'Jet black', hairLength: 0.4, hairVolume: 0.55, curl: 0.3, eyeColor: 'Brown', browStyle: 'thick', browThickness: 0.65, lashLength: 0.55, makeupStyle: 'none', lipColor: 0.4, blush: 0.15, bodyHair: 0.4, beard: 'stubble', outfit: 'casual', outfitColor: '#a33b2a', outfitColor2: '#2d3646' },
      bio: 'Sous-chef with forearms of steel and calves that beg to differ.' },
    { id: 'kenji', name: 'Kenji', game: 'man', pron: 'he/him', age: 38, h: 172, build: 'slim', anc: [0, 0.97, 0.03], look: 'prettyboy', lk: 0.45,
      face: { epicanthus: 0.3, eyefold: -0.3, nosebridge: -0.1, jawline: 0.25, cheekbones: 0.2, headage: 0.1, 'head-rectangular': 0.2 },
      fig: { shoulders: 0.05, vshape: 0.15, pecs: 0.1, forearm: 0.35, armmuscle: 0.2, belly: -0.15 },
      p: { gender: 0.95, weight: 0.42, muscle: 0.6, proportions: 0.62, skinTone: 0.24, undertone: 0.55, breastSize: 0.5, breastFirmness: 0.5, hairStyle: 'medium', hairColor: 'Soft black', hairLength: 0.55, hairVolume: 0.5, curl: 0.05, eyeColor: 'Dark brown', browStyle: 'straight', browThickness: 0.55, lashLength: 0.5, makeupStyle: 'none', lipColor: 0.38, blush: 0.15, bodyHair: 0.12, moles: 0.25, beard: 'none', outfit: 'formal', outfitColor: '#46546b', outfitColor2: '#22252c' },
      bio: 'Furniture maker who carves for hours and forgets his back exists.' },
    { id: 'owen', name: 'Owen', game: 'man', pron: 'he/him', age: 27, h: 184, build: 'tall', anc: [0, 0, 1], look: 'rugged', lk: 0.5,
      face: { cheekbones: 0.2, nosetip: 0.05, mouthwidth: 0.05, 'head-oval': 0.15, jawline: 0.1 },
      fig: { shoulders: 0.3, vshape: 0.3, pecs: 0.2, thighmuscle: 0.3, glutes: 0.2, belly: -0.25, upperleglen: 0.15 },
      p: { gender: 0.98, weight: 0.5, muscle: 0.7, proportions: 0.68, skinTone: 0.04, undertone: 0.45, breastSize: 0.5, breastFirmness: 0.5, freckles: 0.4, hairStyle: 'crew', hairColor: 'Copper red', hairLength: 0.4, hairVolume: 0.5, curl: 0.2, eyeColor: 'Blue', browStyle: 'natural', browThickness: 0.5, lashLength: 0.5, makeupStyle: 'none', lipColor: 0.4, blush: 0.25, bodyHair: 0.3, beard: 'stubble', outfit: 'sport', outfitColor: '#6b2d3a', outfitColor2: '#22252c' },
      bio: 'Rugby full-back and data analyst from Cardiff.' },
    { id: 'andre', name: 'Andre', game: 'man', pron: 'he/him', age: 58, h: 181, build: 'stocky', anc: [0.85, 0, 0.15], look: 'rugged', lk: 0.5,
      face: { headage: 0.4, laughlines: 0.4, eyebags: 0.25, nosewidth: 0.3, upperlip: 0.2, lowerlip: 0.2, 'head-round': 0.15 },
      fig: { belly: 0.3, waist: 0.25, shoulders: 0.2, pecs: 0.1, neckthick: 0.25, doublechin: 0.1, 'shape-mapple': 0.3 },
      p: { gender: 1, weight: 0.68, muscle: 0.55, proportions: 0.55, skinTone: 0.76, undertone: 0.5, breastSize: 0.5, breastFirmness: 0.4, hairStyle: 'buzz', hairColor: 'Grey', hairLength: 0.15, hairVolume: 0.4, curl: 0.9, eyeColor: 'Brown', browStyle: 'natural', browThickness: 0.55, lashLength: 0.45, makeupStyle: 'none', lipColor: 0.4, blush: 0.12, bodyHair: 0.35, moles: 0.2, beard: 'short', outfit: 'formal', outfitColor: '#e8e2d6', outfitColor2: '#2d3646' },
      bio: 'Jazz pianist with sixty years of music in his hands and a back that remembers every gig.' },
    // ------------------------------------------------------------ non-binary
    { id: 'river', name: 'River', game: 'nonbinary', pron: 'they/them', age: 28, h: 171, build: 'slim', anc: [0, 0, 1], look: 'prettyboy', lk: 0.5,
      face: { cheekbones: 0.25, jawwidth: -0.1, nosetip: 0.05, upperlip: 0.05, 'head-oval': 0.2 },
      fig: { waist: -0.2, belly: -0.3, hips: 0.05, glutes: 0.15, shoulders: -0.05 },
      p: { gender: 0.45, weight: 0.38, muscle: 0.5, proportions: 0.68, skinTone: 0.08, undertone: 0.45, breastSize: 0.4, breastFirmness: 0.6, freckles: 0.15, moles: 0.25, hairStyle: 'short', hairColor: 'Pastel pink', hairLength: 0.4, hairVolume: 0.55, curl: 0.15, eyeColor: 'Grey', browStyle: 'straight', browThickness: 0.45, lashLength: 0.6, makeupStyle: 'graphic liner', makeup: 0.5, lipColor: 0.4, blush: 0.25, bodyHair: 0.08, nailColor: '#1e1e22', outfit: 'casual', outfitColor: '#1e1e22', outfitColor2: '#22252c' },
      bio: 'Tattoo artist with a waitlist months long.' },
    { id: 'sasha', name: 'Sasha', game: 'nonbinary', pron: 'they/them', age: 25, h: 167, build: 'athletic', anc: [0, 0.45, 0.55], look: 'pretty', lk: 0.5,
      face: { epicanthus: 0.15, cheekbones: 0.25, jawline: 0.15, nosebridge: -0.05, 'head-diamond': 0.15 },
      fig: { shoulders: 0.2, lats: 0.2, waist: -0.25, belly: -0.35, armmuscle: 0.35, forearm: 0.3, glutes: 0.25, thighmuscle: 0.2 },
      p: { gender: 0.4, weight: 0.4, muscle: 0.8, proportions: 0.65, skinTone: 0.14, undertone: 0.5, breastSize: 0.4, breastFirmness: 0.62, hairStyle: 'bob', hairColor: 'Platinum', hairLength: 0.4, hairVolume: 0.45, curl: 0.05, eyeColor: 'Grey', browStyle: 'natural', browThickness: 0.45, lashLength: 0.6, makeupStyle: 'none', lipColor: 0.4, blush: 0.3, bodyHair: 0.06, outfit: 'sport', outfitColor: '#7a6a9a', outfitColor2: '#22252c' },
      bio: 'Aerial-silks performer with the shoulders of a gymnast.' },
    { id: 'akira', name: 'Akira', game: 'nonbinary', pron: 'they/them', age: 32, h: 169, build: 'average', anc: [0, 0.96, 0.04], look: 'prettyboy', lk: 0.45,
      face: { epicanthus: 0.35, eyefold: -0.3, nosebridge: -0.2, cheekvolume: 0.1, 'head-round': 0.15, mouthwidth: 0.05 },
      fig: { waist: -0.05, belly: 0, hips: 0.1, glutes: 0.15, thighs: 0.1 },
      p: { gender: 0.55, weight: 0.52, muscle: 0.5, proportions: 0.55, skinTone: 0.25, undertone: 0.58, breastSize: 0.42, breastFirmness: 0.55, hairStyle: 'medium', hairColor: 'Jet black', hairLength: 0.5, hairVolume: 0.55, curl: 0.05, eyeColor: 'Dark brown', browStyle: 'straight', browThickness: 0.55, lashLength: 0.55, makeupStyle: 'natural', makeup: 0.3, lipColor: 0.42, blush: 0.25, bodyHair: 0.1, moles: 0.2, outfit: 'casual', outfitColor: '#2f5a4a', outfitColor2: '#c9b79c' },
      bio: 'Ramen-shop owner who is on their feet from dawn to midnight.' },
    { id: 'sage', name: 'Sage', game: 'nonbinary', pron: 'they/them', age: 30, h: 165, build: 'plus', anc: [0.15, 0.45, 0.4], look: 'soft', lk: 0.5,
      face: { nosebridge: 0.1, cheekbones: 0.3, upperlip: 0.1, lowerlip: 0.1, 'head-round': 0.1 },
      fig: { waist: 0.2, belly: 0.25, hips: 0.4, glutes: 0.4, thighs: 0.4, armfat: 0.25, breastpos: -0.15 },
      p: { gender: 0.4, weight: 0.85, muscle: 0.42, proportions: 0.5, skinTone: 0.44, undertone: 0.62, breastSize: 0.62, breastFirmness: 0.45, hairStyle: 'braid', hairColor: 'Dark brown', hairLength: 0.9, hairVolume: 0.55, curl: 0.15, eyeColor: 'Brown', browStyle: 'thick', browThickness: 0.6, lashLength: 0.6, makeupStyle: 'none', lipColor: 0.42, blush: 0.3, bodyHair: 0.1, outfit: 'casual', outfitColor: '#8a7356', outfitColor2: '#2d3646' },
      bio: 'Herbalist and potter who always smells faintly of cedar.' },
    // ------------------------------------------------------------ trans men
    { id: 'elliot', name: 'Elliot', game: 'transman', pron: 'he/him', age: 26, h: 171, build: 'slim', anc: [0, 0, 1], look: 'prettyboy', lk: 0.6,
      face: { jawline: 0.2, jawwidth: 0.1, cheekbones: 0.15, browridge: 0.1, 'head-oval': 0.15 },
      fig: { shoulders: 0.1, vshape: 0.15, waist: -0.1, belly: -0.3, hips: -0.05, calfmuscle: 0.3 },
      p: { gender: 0.82, weight: 0.4, muscle: 0.62, proportions: 0.62, skinTone: 0.1, undertone: 0.48, breastSize: 0.35, breastFirmness: 0.55, freckles: 0.1, hairStyle: 'crew', hairColor: 'Light brown', hairLength: 0.4, hairVolume: 0.5, curl: 0.1, eyeColor: 'Blue', browStyle: 'natural', browThickness: 0.55, lashLength: 0.55, makeupStyle: 'none', lipColor: 0.4, blush: 0.2, bodyHair: 0.2, beard: 'stubble', outfit: 'sport', outfitColor: '#c94f4f', outfitColor2: '#22252c' },
      bio: 'Bike courier who knows every pothole in the city by name.' },
    { id: 'rowan', name: 'Rowan', game: 'transman', pron: 'he/him', age: 34, h: 176, build: 'muscular', role: 'guard', anc: [0.92, 0, 0.08], look: 'rugged', lk: 0.6,
      face: { nosewidth: 0.25, upperlip: 0.2, lowerlip: 0.2, cheekbones: 0.15 },
      fig: { shoulders: 0.4, vshape: 0.45, pecs: 0.4, lats: 0.35, armmuscle: 0.45, biceps: 0.25, forearm: 0.3, belly: -0.3, thighmuscle: 0.3, neckthick: 0.2 },
      p: { gender: 0.86, weight: 0.55, muscle: 0.9, proportions: 0.68, skinTone: 0.74, undertone: 0.52, breastSize: 0.32, breastFirmness: 0.55, hairStyle: 'buzz', hairColor: 'Jet black', hairLength: 0.2, hairVolume: 0.5, curl: 0.9, eyeColor: 'Dark brown', browStyle: 'thick', browThickness: 0.6, lashLength: 0.5, makeupStyle: 'none', lipColor: 0.4, blush: 0.12, bodyHair: 0.3, beard: 'short', outfit: 'sport', outfitColor: '#1f2a44', outfitColor2: '#2b2d33' },
      bio: 'Personal trainer who pushes everyone hard and forgets to stretch himself.' },
    { id: 'kaito', name: 'Kaito', game: 'transman', pron: 'he/him', age: 23, h: 168, build: 'slim', anc: [0, 0.95, 0.05], look: 'prettyboy', lk: 0.65,
      face: { epicanthus: 0.3, eyefold: -0.3, nosebridge: -0.15, jawline: 0.15, cheekbones: 0.15, 'head-oval': 0.1 },
      fig: { shoulders: 0.05, waist: -0.1, belly: -0.3, hips: -0.05, glutes: 0.1 },
      p: { gender: 0.78, weight: 0.4, muscle: 0.55, proportions: 0.6, skinTone: 0.22, undertone: 0.55, breastSize: 0.34, breastFirmness: 0.55, hairStyle: 'short', hairColor: 'Dark brown', hairLength: 0.45, hairVolume: 0.55, curl: 0.05, eyeColor: 'Dark brown', browStyle: 'straight', browThickness: 0.55, lashLength: 0.55, makeupStyle: 'none', lipColor: 0.42, blush: 0.25, bodyHair: 0.12, outfit: 'casual', outfitColor: '#3b5c8a', outfitColor2: '#d9d4cc' },
      bio: 'Coffee roaster by day, DJ on Saturday nights.' },
    // ------------------------------------------------------------ genderfluid
    { id: 'alex', name: 'Alex', game: 'genderfluid', pron: 'she/they', age: 27, h: 170, build: 'athletic', anc: [0.15, 0.25, 0.6], look: 'pretty', lk: 0.55,
      face: { cheekbones: 0.2, jawline: 0.15, nosebridge: 0.05, upperlip: 0.1, lowerlip: 0.1, 'head-oval': 0.15 },
      fig: { shoulders: 0.15, waist: -0.25, belly: -0.3, hips: 0.15, glutes: 0.35, thighs: 0.15, armmuscle: 0.25 },
      p: { gender: 0.35, weight: 0.45, muscle: 0.72, proportions: 0.65, skinTone: 0.34, undertone: 0.6, breastSize: 0.45, breastFirmness: 0.6, hairStyle: 'ponytail', hairColor: 'Auburn', hairLength: 0.6, hairVolume: 0.55, curl: 0.3, eyeColor: 'Hazel', browStyle: 'natural', browThickness: 0.55, lashLength: 0.7, makeupStyle: 'smoky eye', makeup: 0.5, lipColor: 0.45, blush: 0.25, bodyHair: 0.06, moles: 0.2, outfit: 'casual', outfitColor: '#1e1e22', outfitColor2: '#6b2d3a' },
      bio: 'Stage-combat choreographer; the bruises are a job hazard.' },
    { id: 'nao', name: 'Nao', game: 'genderfluid', pron: 'he/they', age: 24, h: 166, build: 'slim', anc: [0, 0.95, 0.05], look: 'prettyboy', lk: 0.6,
      face: { epicanthus: 0.35, eyefold: -0.3, nosebridge: -0.2, jawwidth: -0.1, cheekbones: 0.15, 'head-oval': 0.15 },
      fig: { waist: -0.25, belly: -0.3, hips: 0.1, glutes: 0.2, shoulders: -0.1 },
      p: { gender: 0.55, weight: 0.38, muscle: 0.45, proportions: 0.62, skinTone: 0.18, undertone: 0.52, breastSize: 0.44, breastFirmness: 0.6, hairStyle: 'bob', hairColor: 'Blue', hairLength: 0.5, hairVolume: 0.5, curl: 0.05, eyeColor: 'Dark brown', browStyle: 'straight', browThickness: 0.45, lashLength: 0.65, makeupStyle: 'everyday', makeup: 0.45, lipColor: 0.45, blush: 0.35, bodyHair: 0.04, outfit: 'casual', outfitColor: '#e8e2d6', outfitColor2: '#2b4f9c' },
      bio: 'Vintage-clothing reseller who never wears the same look twice.' },
    { id: 'charlie', name: 'Charlie', game: 'genderfluid', pron: 'she/they', age: 31, h: 168, build: 'curvy', anc: [0, 0, 1], look: 'girlnextdoor', lk: 0.6,
      face: { cheekvolume: 0.1, nosetip: 0.1, upperlip: 0.05, dimples: 0.2, 'head-round': 0.1 },
      fig: { waist: -0.15, belly: 0, hips: 0.35, glutes: 0.4, thighs: 0.35, 'shape-pear': 0.35, breastpos: -0.05 },
      p: { gender: 0.3, weight: 0.6, muscle: 0.45, proportions: 0.58, skinTone: 0.06, undertone: 0.45, breastSize: 0.58, breastFirmness: 0.52, freckles: 0.3, hairStyle: 'wavy', hairColor: 'Dark blonde', hairLength: 0.55, hairVolume: 0.6, curl: 0.35, eyeColor: 'Grey-green', browStyle: 'natural', browThickness: 0.45, lashLength: 0.65, makeupStyle: 'natural', makeup: 0.35, lipColor: 0.45, blush: 0.4, bodyHair: 0.05, outfit: 'casual', outfitColor: '#c9b79c', outfitColor2: '#2f5a4a' },
      bio: 'Pub-quiz champion and part-time bookbinder from Edinburgh.' },
  ];

  BS.CAST = L.map((c) => ({
    id: 'cast-' + c.id, name: c.name, game: c.game, identity: BSID[c.game] || 'nonbinary', pronouns: c.pron,
    age: c.age, heightCm: c.h, build: c.build, buildLabel: BUILD_LABEL[c.build] || 'Average', role: c.role || '', bio: c.bio,
    params: make(c),
  }));
  BS.CAST_BY_ID = {};
  for (const c of BS.CAST) BS.CAST_BY_ID[c.id] = c;
  // a fresh copy of a cast member's params, ready to load or hand to the game
  BS.castParams = (id) => { const c = BS.CAST_BY_ID[id]; return c ? JSON.parse(JSON.stringify(c.params)) : null; };
})();
